# Generated by Django 5.1.6 on 2025-04-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostfounditem',
            name='posted_at',
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=100),
        ),
        migrations.AddField(
            model_name='lostfounditem',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='image',
            field=models.ImageField(upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='item_type',
            field=models.CharField(max_length=20),
        ),
    ]
